# Generated by Django 4.1.7 on 2023-03-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerBTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Введите название парсера')),
                ('stock_market', models.CharField(max_length=500, verbose_name='Ссылка на главную страницу биржи')),
                ('url', models.CharField(max_length=2000, verbose_name='Ссылка на динамику актива BTC')),
                ('comment', models.CharField(max_length=300, verbose_name='Комментарий')),
                ('time_scraping', models.SmallIntegerField(verbose_name='Время работы анализатора в сутках')),
                ('div_class', models.CharField(blank=True, help_text='Укажите div, из которого необходимо получить данные', max_length=300, null=True, verbose_name='div class')),
            ],
            options={
                'verbose_name': 'Анализатор bitcoin',
                'verbose_name_plural': 'Анализаторы bitcoin',
            },
        ),
        migrations.CreateModel(
            name='AnalyzerALT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, verbose_name='Ссылка на динамику актива альткоина')),
                ('div_class', models.CharField(blank=True, help_text='Укажите div, из которого необходимо получить данные', max_length=300, null=True, verbose_name='div class')),
                ('alert', models.CharField(blank=True, max_length=100, null=True, verbose_name='Поле для оповещения пользователя об изменении цены более, чем на 1%')),
                ('analyzer_btc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser.analyzerbtc', verbose_name='Прикреплен к анализатору bitcoin')),
            ],
            options={
                'verbose_name': 'Анализатор altcoin',
                'verbose_name_plural': 'Анализаторы altcoin',
            },
        ),
    ]
