# Generated by Django 4.1.7 on 2023-03-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzeralt',
            options={'verbose_name': 'Анализатор-корректор altcoin', 'verbose_name_plural': 'Анализаторы-корректоры altcoin'},
        ),
        migrations.AddField(
            model_name='analyzeralt',
            name='dependence',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Зависимость цены от цены bitcoin'),
        ),
    ]
